---
title: "Smart Industry"
---

<hr>
<iframe width="560" height="315" src="https://www.youtube.com/embed/rt65167tZlQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>
Manufacturing innovation trends - how manufacturing is changing - Future of Manufacturing 4.0 Keynote Speaker. Lessons from Toyota assembly lines for fork lift trucks.  How to optimise factory production with just-in-time and hundreds of small enhancements with huge total impact, using predictive analytics and Big Data.  How to harness human genius in the workforce to make things faster and more reliably.  Key manufacturing trends presented by Futurist keynote speaker Patrick Dixon - tour of Toyota factory site in Mjölby, Sweden.
<hr>

<iframe width="560" height="315" src="https://www.youtube.com/embed/7dYtrncuQpU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>
When Arrival went public in March 2021, despite not yet having a vehicle on the road, they were recognised as Britain's most 'valuable' company making founder Denis Sverdlov a billionaire after trading opened.

Since our visit to Arrival last July we have been desperate to return to their R&D centre in Banbury  to see how their electric van and bus designs have developed. Whilst still a prototype, the bus has come a long way with a flexible, modular design aimed at pleasing both the rider and the driver. The delivery van has been moderated to meet universal demands but has kept its ability to carry huge amounts of cargo with incredible visibility. 

What Arrival are doing is revolutionary. They are not just looking at the designs of the vehicles to ensure they are scalable, it's the way they plan to make them using robots within micro-factories that set them apart. With Arrival moving at speed towards production we cannot wait to see what they do next.

<hr>